# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 1
    open-pull-requests-limit: 999
    groups:
      artifacts:
        patterns:
          - 'actions/*-artifact'
      caches:
        patterns:
          - 'actions/cache'
          - 'actions/cache/*'
          - 'awalsh128/cache-apt-pkgs-action'
      ci-cd:
        patterns:
          - 'dependabot/*'
          - 'actions/create-github-app-token'
      sast:
        patterns:
          - 'github/codeql-*'
          - 'actions/dependency-review-action'
          - 'step-security/*'
          - 'microsoft/security-devops-action'
          - 'microsoft/DevSkim-Action'
          - 'ossf/*'
      setup:
        patterns:
          - 'actions/checkout'
          - 'actions/setup-*'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      semver-major-days: 30
      default-days: 1
    versioning-strategy: increase
    open-pull-requests-limit: 999
    ignore:
      # Match lts/*
      - dependency-name: '@types/node'
        versions:
          - '>=25.0.0'
      # All tutorials use v9. Keep it on v9 until I get around to figuring out breaking upgrade
      - dependency-name: '@simplewebauthn/*'
        versions:
          - '>=10.0.0'
    groups:
      cloudflare:
        patterns:
          - 'cloudflare'
          - '@cloudflare/*'
          - 'wrangler'
        exclude-patterns:
          - '@cloudflare/workers-types'
      code-management:
        patterns:
          - 'prettier'
          - 'prettier-plugin-*'
          - '@demosjarco/prettier-config'
          - 'eslint'
          - '@eslint/*'
          - 'eslint-plugin-*'
          - 'eslint-config-*'
          - 'typescript-eslint'
          - '@microsoft/eslint-formatter-sarif'
      typescript-core:
        patterns:
          - 'typescript'
          - 'tsx'
      typescript-types:
        patterns:
          - '@types/*'
          - '@cloudflare/workers-types'
          - 'turnstile-types'
      validation:
        patterns:
          - 'zod'
          - 'validator'
