name = "autosec-eaas"
pages_build_output_dir = "dist"
compatibility_date = "2025-01-29"
compatibility_flags = ["nodejs_compat_v2"]
upload_source_maps = true
d1_databases = [
    { binding = "EAAS_ROOT", database_name = "eaas_root_p", database_id = "74b7a7fd-18ea-422f-a888-47214742e4cf" },
]
services = [
    { binding = "SIDECAR_WORKER", service = "eaas-sidecar" },
    # Not yet published
    # { binding = "SIDECAR_WORKER", service = "eaas-sidecar-preview" },
]


[vars]
SKIP_DEPENDENCY_INSTALL = "1"
NODE_ENV = "development"
TURNSTILE_SITE_KEY = "0x4AAAAAAAzwYTLxe176o9ss"


[env.production]
compatibility_date = "2025-01-29"
compatibility_flags = ["nodejs_compat_v2"]
upload_source_maps = false
d1_databases = [
    # { binding = "EAAS_ROOT", database_name = "eaas_root", database_id = "c576d6cf-f202-4845-a971-f95d0e00e95a" },
    { binding = "EAAS_ROOT", database_name = "eaas_root_p", database_id = "74b7a7fd-18ea-422f-a888-47214742e4cf" },
]
services = [{ binding = "SIDECAR_WORKER", service = "eaas-sidecar" }]

[env.production.vars]
SKIP_DEPENDENCY_INSTALL = "1"
NODE_ENV = "production"
TURNSTILE_SITE_KEY = "0x4AAAAAAAzwYTLxe176o9ss"


[dev]
local_protocol = "http"
ip = "localhost"
port = 7016
