name = "autosec-eaas"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat_v2"]
upload_source_maps = true
d1_databases = [
    { binding = "DB", database_name = "eaas", database_id = "49780132-5d17-4dc9-a332-ed6f696054f0" },
]
services = [{ binding = "SIDECAR_WORKER", service = "eaas-sidecar-preview" }]


[vars]
SKIP_DEPENDENCY_INSTALL = "1"
NODE_ENV = "development"
TURNSTILE_SITE_KEY = "0x4AAAAAAAzwYTLxe176o9ss"


[env.production]
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat_v2"]
upload_source_maps = false
d1_databases = [
    { binding = "DB", database_name = "eaas", database_id = "4e4077c0-ef92-45db-b2ef-7401b87751a0", preview_database_id = "49780132-5d17-4dc9-a332-ed6f696054f0" },
]
services = [{ binding = "SIDECAR_WORKER", service = "eaas-sidecar" }]

[env.production.vars]
SKIP_DEPENDENCY_INSTALL = "1"
NODE_ENV = "production"
TURNSTILE_SITE_KEY = "0x4AAAAAAAzwYTLxe176o9ss"


[dev]
local_protocol = "https"
ip = "localhost"
port = 7016
