name = "autosec-eaas"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat_v2"]
upload_source_maps = true
d1_databases = [
    { binding = "EAAS_ROOT", database_name = "eaas_root_p", database_id = "fd2c6d75-b6d9-4a6e-8bca-bbce33682dc5" },
]
services = [{ binding = "SIDECAR_WORKER", service = "eaas-sidecar-preview" }]


[vars]
SKIP_DEPENDENCY_INSTALL = "1"
NODE_ENV = "development"
TURNSTILE_SITE_KEY = "0x4AAAAAAAzwYTLxe176o9ss"


[env.production]
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat_v2"]
upload_source_maps = false
d1_databases = [
    # { binding = "EAAS_ROOT", database_name = "eaas_root", database_id = "c576d6cf-f202-4845-a971-f95d0e00e95a" },
    { binding = "EAAS_ROOT", database_name = "eaas_root_p", database_id = "fd2c6d75-b6d9-4a6e-8bca-bbce33682dc5" },
]
services = [{ binding = "SIDECAR_WORKER", service = "eaas-sidecar" }]

[env.production.vars]
SKIP_DEPENDENCY_INSTALL = "1"
NODE_ENV = "production"
TURNSTILE_SITE_KEY = "0x4AAAAAAAzwYTLxe176o9ss"


[dev]
local_protocol = "http"
ip = "localhost"
port = 7016
