name = "eaas-sidecar-preview"
main = "src/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = false
preview_urls = false
minify = true
upload_source_maps = true

[vars]
NODE_ENV = "development"

[observability]
enabled = true


[env.production]
name = "eaas-sidecar"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = false
preview_urls = false
minify = true
upload_source_maps = false

[env.production.vars]
NODE_ENV = "production"

[env.production.observability]
enabled = true


[dev]
local_protocol = "http"
ip = "localhost"
