name = "eaas-api-preview"
main = "src/index.ts"
compatibility_date = "2025-01-24"
compatibility_flags = ["nodejs_compat_v2"]
route = { pattern = "preview.api.eaas.autosec.network", custom_domain = true }
workers_dev = false
preview_urls = false
minify = true
upload_source_maps = true
version_metadata = { binding = "CF_VERSION_METADATA" }
workflows = [
    { name = "data-key-rotation-preview", binding = "DATA_KEY_ROTATION", class_name = "DataKeyRotation" },
]
d1_databases = [
    { binding = "EAAS_ROOT", database_name = "eaas_root_p", database_id = "74b7a7fd-18ea-422f-a888-47214742e4cf" },
    # VipBindingsPreview
    { binding = "98573F5FF41FFAEDCC34D6E8A143276A527827F519D617E511C55681C1BB4DED", database_id = "b55a31ba-b382-4f53-b204-2d730ee6c3aa" },
]

[vars]
ENVIRONMENT = "preview"
NODE_ENV = "development"

[observability]
enabled = true

[placement]
mode = "smart"


[env.production]
name = "eaas-api"
compatibility_date = "2025-01-24"
compatibility_flags = ["nodejs_compat_v2"]
route = { pattern = "api.eaas.autosec.network", custom_domain = true }
workers_dev = false
preview_urls = false
minify = true
upload_source_maps = true
version_metadata = { binding = "CF_VERSION_METADATA" }
workflows = [
    { name = "data-key-rotation", binding = "DATA_KEY_ROTATION", class_name = "DataKeyRotation" },

]
d1_databases = [
    # { binding = "EAAS_ROOT", database_name = "eaas_root", database_id = "c576d6cf-f202-4845-a971-f95d0e00e95a" },
    { binding = "EAAS_ROOT", database_name = "eaas_root_p", database_id = "74b7a7fd-18ea-422f-a888-47214742e4cf" },
    # VipBindingsProd
    # VipBindingsPreview
    { binding = "98573F5FF41FFAEDCC34D6E8A143276A527827F519D617E511C55681C1BB4DED", database_id = "b55a31ba-b382-4f53-b204-2d730ee6c3aa" },
]

[env.production.vars]
ENVIRONMENT = "preview"
NODE_ENV = "development"

[env.production.observability]
enabled = true

[env.production.placement]
mode = "smart"


[dev]
local_protocol = "http"
ip = "localhost"
