name = "eaas-api-preview"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = false
route = { pattern = "preview.api.eaas.autosec.network", custom_domain = true }
minify = true
upload_source_maps = true
version_metadata = { binding = "CF_VERSION_METADATA" }
d1_databases = [
    { binding = "EAAS_ROOT", database_name = "eaas_root_p", database_id = "74b7a7fd-18ea-422f-a888-47214742e4cf" },
    # VipBindingsPreview
    { binding = "A1C64BAC8BEB2FD34541EB5F35B15B66EA0F21227F449A4E59F6816902A96530", database_id = "b8777faa-c242-4427-a1b7-eca2b59897be" },
]

[vars]
ENVIRONMENT = "preview"
NODE_ENV = "development"

[observability]
enabled = true

[placement]
mode = "smart"


[env.production]
name = "eaas-api"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = false
route = { pattern = "api.eaas.autosec.network", custom_domain = true }
minify = true
upload_source_maps = true
version_metadata = { binding = "CF_VERSION_METADATA" }
d1_databases = [
    # { binding = "EAAS_ROOT", database_name = "eaas_root", database_id = "c576d6cf-f202-4845-a971-f95d0e00e95a" },
    { binding = "EAAS_ROOT", database_name = "eaas_root_p", database_id = "74b7a7fd-18ea-422f-a888-47214742e4cf" },
    # VipBindingsProd
]

[env.production.vars]
ENVIRONMENT = "preview"
NODE_ENV = "development"

[env.production.observability]
enabled = true

[env.production.placement]
mode = "smart"


[dev]
local_protocol = "http"
ip = "localhost"
