name: Release
on:
  push:
    branches:
      - production
    paths:
      - '.github/workflows/changeset-release.yml'
      - '.changeset/**'
      - 'api/CHANGELOG.md'
      - 'api/package.json'
      - 'frontend/CHANGELOG.md'
      - 'frontend/package.json'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-sudo: true
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-tags: true # Important to fetch all history for versioning
      - run: git config set --type=bool push.autoSetupRemote true
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --include-workspace-root
      - uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
