name: Release
on:
  push:
    branches:
      - production
    paths:
      - '.github/workflows/changeset-release.yml'
      - '.changeset/**'
      - 'api/CHANGELOG.md'
      - 'api/package.json'
      - 'frontend/CHANGELOG.md'
      - 'frontend/package.json'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-sudo-and-containers: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-tags: true # Important to fetch all history for versioning
      - run: git config set --type=bool push.autoSetupRemote true
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --include-workspace-root
      - uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
