name: D1 Migrate Preview

on:
  push:
    paths:
      - '.github/workflows/db-migrate-preview.yml'
      - 'shared/db-preview/schemas/**'
      - 'shared/db-preview/cli*'
  workflow_dispatch:
    inputs:
      remote:
        description: Actually apply migrations to live preview databases
        type: boolean
        default: true
        required: true
      root:
        type: boolean
        default: true
        required: true
      tenant:
        type: boolean
        default: true
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - run: npm ci --include-workspace-root
      - run: npm run cli:pre -- generate ${{ github.event_name == 'workflow_dispatch' && (inputs.root && '--type root' || '') || '--type root' }} ${{ github.event_name == 'workflow_dispatch' && (inputs.tenant && '--type tenant' || '') || '--type tenant' }}
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add shared/db-preview/schemas/*/*.sql
      - run: git add shared/db-preview/schemas/*/meta/*.json
      - run: git commit -m "Generated migrations" || echo "migration files not touched"
      - run: git push
      - run: npm run cli:pre -- migrate --remote ${{ inputs.remote }} ${{ inputs.root && '--type root' || '' }} ${{ inputs.tenant && '--type tenant' || '' }}
        if: github.event_name == 'workflow_dispatch'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CICD_CF_API_TOKEN: ${{ secrets.CICD_CF_API_TOKEN }}
