name: ESLint

on:
  push:
    paths:
      - '.github/workflows/eslint.yml'
      - 'eslint.config.mjs'
      - '**/eslint.config.mjs'
      - 'package*.json'
      - '**/package*.json'
      - '**/*.ts*'
  pull_request:
    paths:
      - '.github/workflows/eslint.yml'
      - 'eslint.config.mjs'
      - '**/eslint.config.mjs'
      - 'package*.json'
      - '**/package*.json'
      - '**/*.ts*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: read
    steps:
      - uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-sudo-and-containers: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --ignore-scripts --include-workspace-root --workspaces
      - run: npm run-script install --if-present --include-workspace-root --workspaces
      - run: npm --workspace types run build
      - run: npm --workspace db run build
      - run: npm --workspace helpers run build
      - run: npm run lint:fix
        continue-on-error: true
      - name: Check for Changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      - run: git add --all
        if: steps.changes.outputs.changes == 'true'
      - name: Don't touch package files
        if: steps.changes.outputs.changes == 'true'
        run: |
          git reset -- package*.json
          git reset -- **/package*.json
      - name: Git Setup
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git commit -m "Ran linter"
        if: steps.changes.outputs.changes == 'true'
        continue-on-error: true
      - run: git push
        if: steps.changes.outputs.changes == 'true'
        continue-on-error: true
      - run: npm install -D @microsoft/eslint-formatter-sarif
      - run: npm run lint -- --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true
      - uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        with:
          sarif_file: eslint-results.sarif
