name: ESLint

on:
  push:
    paths:
      - '.github/workflows/eslint.yml'
      - 'eslint.config.mjs'
      - '**/eslint.config.mjs'
      - 'package*.json'
      - '**/package*.json'
      - '**/*.ts*'
  pull_request:
    paths:
      - '.github/workflows/eslint.yml'
      - 'eslint.config.mjs'
      - '**/eslint.config.mjs'
      - 'package*.json'
      - '**/package*.json'
      - '**/*.ts*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: read
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-sudo-and-containers: true
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --ignore-scripts --include-workspace-root --workspaces
      - run: npm run-script install --if-present --include-workspace-root --workspaces
      - run: npm --workspace types run build
      - parallel:
          - run: npm --workspace db run build
          - run: npm --workspace helpers run build
      - run: npm run lint:fix
        continue-on-error: true
      - name: Check for Changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      - run: git add --all
        if: steps.changes.outputs.changes == 'true'
      - name: Don't touch package files
        if: steps.changes.outputs.changes == 'true'
        run: |
          git reset -- package*.json
          git reset -- **/package*.json
      - run: git commit -m "Ran linter"
        if: steps.changes.outputs.changes == 'true'
        continue-on-error: true
      - run: git push
        if: steps.changes.outputs.changes == 'true'
        continue-on-error: true
      - run: npm run lint -- --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true
      - uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        with:
          sarif_file: eslint-results.sarif
