name: ESLint

on:
  push:
    paths:
      - '.github/workflows/eslint.yml'
      - '.eslintrc.cjs'
      - '**/.eslintrc.cjs'
      - 'package*.json'
      - '**/package*.json'
      - '**/*.ts*'
  pull_request:
    paths:
      - '.github/workflows/eslint.yml'
      - '.eslintrc.cjs'
      - '**/.eslintrc.cjs'
      - 'package*.json'
      - '**/package*.json'
      - '**/*.ts*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: read
    steps:
      - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-sudo: true
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm install -D eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-plugin-qwik
      - run: npm run lint:fix
        continue-on-error: true
      - name: Check for Changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      - run: git add --all
        if: steps.changes.outputs.changes == 'true'
      - name: Don't touch package files
        if: steps.changes.outputs.changes == 'true'
        run: |
          git reset -- package*.json
          git reset -- **/package*.json
      - name: Git Setup
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git commit -m "Ran linter"
        if: steps.changes.outputs.changes == 'true'
        continue-on-error: true
      - run: git push
        if: steps.changes.outputs.changes == 'true'
        continue-on-error: true
      - run: npm install -D @microsoft/eslint-formatter-sarif
      - run: npm run lint -- --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true
      - uses: github/codeql-action/upload-sarif@4f3212b61783c3c68e8309a0f18a699764811cda # v3.27.1
        with:
          sarif_file: eslint-results.sarif
