name: Cache Nuke

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  delete-cache:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit
          disable-sudo-and-containers: true
      - run: gh cache delete --all --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
