name: Pin `node` `lts/*`

on:
  push:
    paths:
      - 'frontend/.nvmrc'
  pull_request:
    types:
      - opened
    paths:
      - 'frontend/.nvmrc'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  editVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-sudo: true
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        id: sn
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: echo "${{ steps.sn.outputs.node-version }}" > frontend/.nvmrc
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git commit frontend/.nvmrc -m "Fixed node version" || echo "nv change not needed"
      - run: git push
