name: Prettier

on:
  push:
    paths:
      - '**.*js*'
      - '**.*ts*'
      - '**.css'
      - '**.less'
      - '**.scss'
      - '**.html'
      - '**.hbs'
      - '**.json'
      - '**.gql'
      - '**.graphql'
      - '**.md*'
      - '**.yaml'
      - '**.yml'
  pull_request:
    paths:
      - '**.*js*'
      - '**.*ts*'
      - '**.css'
      - '**.less'
      - '**.scss'
      - '**.html'
      - '**.hbs'
      - '**.json'
      - '**.gql'
      - '**.graphql'
      - '**.md*'
      - '**.yaml'
      - '**.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          disable-sudo-and-containers: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --ignore-scripts --include-workspace-root --workspaces
      - run: npm run-script install --if-present --include-workspace-root --workspaces
      - run: npm run fmt:fix
      - name: Check for Changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      - run: git commit -am "Ran formatter" || echo "No formatting done"
        if: steps.changes.outputs.changes == 'true'
      - run: git push
        if: steps.changes.outputs.changes == 'true'
