name: Publish API Gateway

on:
  push:
    branches:
      - production
      - preview
    paths:
      - '.github/workflows/publish-apig.yml'
      - 'workers/api/dist/*/*.cf-apig.openapi.json'
      - 'apiGateway.mts'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to:'
        required: true
        default: 'preview'
        type: environment

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment || github.ref_name }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment || github.ref_name }}
      url: https://${{ (inputs.environment || vars.ENVIRONMENT) != 'production' && format('{0}.', (inputs.environment || vars.ENVIRONMENT)) || '' }}api.sushidata.ai
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-sudo-and-containers: true
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --ignore-scripts --include-workspace-root --workspace api
      - run: npm run-script install --if-present
      - run: npm -w api run publish:static
        env:
          CF_API_TOKEN: ${{ secrets.WORKER_DEPLOY_CF_API_TOKEN }}
          ZONE_ID: ${{ secrets.AUTOSEC_ZONE_ID }}
