name: Publish API

on:
  push:
    branches:
      - production
      - dev
    paths:
      - '.github/workflows/publish-api.yml'
      - 'eslint.config.mjs'
      - 'prettier.config.mjs'
      - 'package*.json'
      - 'tsconfig.json'
      - 'shared/**'
      - 'workers/tsconfig.json'
      - 'workers/api/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to:'
        required: true
        type: environment

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment || github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: ${{ (inputs.environment || github.ref_name) == 'production' && 'production' || 'preview' }}
      url: https://${{ (inputs.environment || vars.ENVIRONMENT) != 'production' && format('{0}.', (inputs.environment || vars.ENVIRONMENT)) || '' }}api.eaas.autosec.network
    steps:
      - uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          disable-sudo-and-containers: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --ignore-scripts --include-workspace-root --workspace api --workspace db --workspace helpers --workspace types
      - run: npm run-script install --if-present --include-workspace-root --workspace api --workspace db --workspace helpers --workspace types
      - run: npm --workspace types run build
      - parallel:
          - run: npm --workspace db run build
          - run: npm --workspace helpers run build
      - run: npm --workspace api run build:types:cf
        if: github.actor != 'autosec-prettier[bot]'
      - run: git commit -m "Generate cf types" workers/api/worker-configuration.d.ts || echo "No type generation done"
        if: github.actor != 'autosec-prettier[bot]'
        background: true
      - run: git push
        if: github.actor != 'autosec-prettier[bot]'
        background: true
        continue-on-error: true
      - run: npm --workspace api run build:static
      - run: git add workers/api/dist/**
      - run: git commit -m "Generated static assets" || echo "static assets not touched"
      - run: git push
        background: true
        continue-on-error: true
      - run: npm --workspace api run lint
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      - name: Get Wrangler Version
        run: echo "wrangler_version=$(npm ls wrangler --depth=0 --json | jq -r '.dependencies.wrangler.version')" >> $GITHUB_OUTPUT
        id: npm_wrangler_version
      - uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        id: wrangler
        with:
          wranglerVersion: ${{ steps.npm_wrangler_version.outputs.wrangler_version }}
          apiToken: ${{ secrets.WORKER_DEPLOY_CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: workers/api
          environment: ${{ (vars.ENVIRONMENT == 'production' && 'prod') || '' }}
          vars: |
            GIT_HASH
            CF_ACCOUNT_ID
            EU_BW_SM_PROJECT_ID
            US_BW_SM_PROJECT_ID
          secrets: |
            CF_API_TOKEN
            EU_BW_SM_ACCESS_TOKEN
            US_BW_SM_ACCESS_TOKEN
        env:
          GIT_HASH: ${{ github.sha }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.API_CF_API_TOKEN }}
          EU_BW_SM_PROJECT_ID: ${{ secrets.EU_BW_SM_PROJECT_ID }}
          US_BW_SM_PROJECT_ID: ${{ secrets.US_BW_SM_PROJECT_ID }}
          EU_BW_SM_ACCESS_TOKEN: ${{ secrets.EU_BW_SM_ACCESS_TOKEN }}
          US_BW_SM_ACCESS_TOKEN: ${{ secrets.US_BW_SM_ACCESS_TOKEN}}
