name: Publish `image_proxy`

on:
  push:
    branches:
      - production
    paths:
      - '.github/workflows/publish-image_proxy.yml'
      - 'eslint.config.mjs'
      - 'prettier.config.mjs'
      - 'package*.json'
      - 'tsconfig.json'
      - 'snippets/tsconfig.json'
      - 'snippets/image_proxy/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  upload-snippet:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit
          disable-sudo-and-containers: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --ignore-scripts --include-workspace-root --workspace=image_proxy
      - run: npm run-script install --if-present --include-workspace-root --workspace image_proxy
      - run: npm --workspace=image_proxy run build
      - run: npm --workspace image_proxy run lint
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      - run: |
          curl --silent --fail-with-body --request PUT \
            --url https://api.cloudflare.com/client/v4/zones/${{ secrets.AUTOSEC_ZONE_ID }}/snippets/image_proxy \
            --header 'Content-Type: multipart/form-data' \
            --header 'Authorization: Bearer ${{ secrets.WORKER_DEPLOY_CF_API_TOKEN }}' \
            --form "files=@${{ github.workspace }}/snippets/image_proxy/dist/worker.js" \
            --form "metadata={\"main_module\": \"worker.js\"}"
